### ISSUE TITLE
pic_mat without barcode/cell name

### ISSUE THREAD

**Issue by LalicJ** [Zhen-Miao/PICsnATAC#12]
Hi, sorry to bother you. I met a error when I ran `chrom_assay <- CreateChromatinAssay(counts = counts,sep = c(":", "-"))`

`Error in CreateAssayObject(counts = data.use, data = data, min.cells = -1,  :
  No cell names (colnames) names present in the input matrix
`
I noticed that the `pic_mat` I generated has no column names, i.e. no cell names. I'm not sure whether can run error because this reason. Any help would be greatly appreciated.@Zhen-Miao

**Comment by Zhen-Miao** [comment]
Thanks for reporting this issue. I have now fixed it. You may consider updating the package by running

`devtools::install_github('Zhen-Miao/PICsnATAC')`

Then rerun the analysis. 
Alternatively, you may consider doing the following to add the cell names manually before supplying the object to Seurat

 `colnames(counts) <- cells`

I hope this helps! 

Best,
Zhen
