### ISSUE TITLE
Slow counting

### ISSUE THREAD

**Issue by ollieeknight** [Zhen-Miao/PICsnATAC#2]
Thanks for this package - excited to test it out. I'm playing around with some 10x data I already have, and will process downstream using Signac. Is there any way to speed up counting, though? I find it quite slow. Maybe some progress info as it processes would also be great.

Thanks a million

Ollie

**Comment by Zhen-Miao** [comment]
Thanks for your interest Ollie,

If you have multiple samples/batches, I recommend you run them individually to speed up. For a typical 10X dataset, it should take less than 10 min to finish. The progress bar is a good idea, I will try to incorporate it and speed the program up. 

Thanks,
Zhen

**Comment by Zhen-Miao** [comment]
Progress bar added.

**Comment by Zhen-Miao** [comment]
progress bar added
