### ISSUE TITLE
No overlap error

### ISSUE THREAD

**Issue by valentinwust** [Zhen-Miao/PICsnATAC#3]
Not sure what to call this, but when there isn't any overlap between the cells in the fragments file and the cell list provided to `PIC_counting`, `f1 <- GenomicRanges::makeGRangesFromDataFrame(f1, keep.extra.columns = T)` just throws an incomprehensible error. In my case the problem was that I gave it the wrong cell barcode list, so I'm not sure it should actually work when there isn't any overlap. But it would make sense to throw an error that tells the user the problem in this case, I had to dig through the source code to find out what this was supposed to tell me:
```
Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or length 1
```
Might make sense to throw a warning when the share of fragments that is kept is very low, and a proper error if it is empty.

**Comment by Zhen-Miao** [comment]
Thanks for the suggestion, I have now included additional checking steps, which will send an error message if no cell barcodes are found in fragment files, or a warning message if fewer than ten cells are found in fragment files
